"""empty message

Revision ID: b23dfe530a36
Revises: 4c4b691cf335
Create Date: 2022-04-16 22:20:18.033625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23dfe530a36'
down_revision = '4c4b691cf335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('meeting_information', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.String(length=500), nullable=False),
    sa.Column('date_of_booking', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_classroom_invitee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.String(length=100), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['virtual_classroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_classroom_invitee')
    op.drop_table('virtual_classroom')
    # ### end Alembic commands ###
